chart errors: add test for ensuring we can marshal/unmarshal json
dollarshaveclub/metahelm pull request #27
Opened 2020-11-10 18:55 UTC by mikeykhalil

2020-11-11 21:06 UTC, wwalexander approved these changes
Looks good to me. However, looking at the references in the code to HelmError, it looks like it's only ever read to call its Error() method ([here](https://github.com/dollarshaveclub/metahelm/blob/85649e9ad70cfe84bd60b5a44e5524de15404124/pkg/metahelm/error.go#L57)), which returns a string anyway. It might be just as simple to make ChartError.HelmError a string and store the results of the Error() method.

2020-11-12 00:08 UTC, mikeykhalil commented
> Looks good to me. However, looking at the references in the code to the HelmError field, it looks like it's only ever read to call its Error() method ([here](https://github.com/dollarshaveclub/metahelm/blob/85649e9ad70cfe84bd60b5a44e5524de15404124/pkg/metahelm/error.go#L57)), which returns a string anyway. It might be just as simple to make ChartError.HelmError a string and store the results of the Error() method, and allow us to keep the error information.

Good point. If we are comfortable changing the type of this field and accept that downstream applications might need to make some updates when bumping versions of metahelm, then we can go with this approach. 

If we wanted to be extra cautious, we could just create a new Field in the ChartError struct (e.g. `HelmErrorMessage`) to store the string, and then still omit the original HelmError. 

Something like 

```
type ChartError struct {
   HelmError error `json:"-"`
   HelmErrorMessage string `json:"helm_error_message"`
   ... 
````

Then consider deprecating the `ChartError.HelmError` and plan to remove it in a later version of metahelm.

2020-11-12 17:29 UTC, bkeroackdsc requested changes

2020-11-12 17:29 UTC, bkeroackdsc commented on pkg/metahelm/error.go
> +	HelmErrorString string `json:"error"`
The JSON tag should be more descriptive. `helm_error_string` for example.

2020-11-12 17:29 UTC, bkeroackdsc commented on pkg/metahelm/error.go
> +		HelmErrorString:   err.Error(),
Check `err` for nil before calling any methods on it. If it is nil, this field should be an empty string.

2020-11-12 18:23 UTC, bkeroackdsc approved these changes

2020-11-20 19:53 UTC, merged