Upgrade to Helm 3 v3.6.0
dollarshaveclub/metahelm pull request #31
Opened 2021-07-28 17:23 UTC by esterlinej

This is branched from the closed PR: https://github.com/dollarshaveclub/metahelm/pull/28, with specific updates improving install command line options, and other fixes.

2021-07-28 17:35 UTC, bkeroackdsc requested changes

2021-07-28 17:35 UTC, bkeroackdsc commented on pkg/metahelm/metahelm.go
> +	// TODO: Process opts
Still needed?

2021-07-28 17:35 UTC, bkeroackdsc commented on pkg/metahelm/metahelm.go
> +			release, err2 = get.Run(ops.releaseNamePrefix + c.Title)
You need to pass the release name through to this function, since it might be truncated with a random number appended.

2021-07-28 23:35 UTC, bkeroackdsc requested changes

2021-07-28 23:35 UTC, bkeroackdsc commented on pkg/metahelm/metahelm.go
> +			release, err2 = get.Run(ReleaseName(ops.releaseNamePrefix + c.Title))
This won't work because `ReleaseName()` will return a different random number than when the release was first created if it has to truncate. You'll need to pass through the previously-generated name to this function.

2021-07-28 23:42 UTC, esterlinej commented on pkg/metahelm/metahelm.go
> +			release, err2 = get.Run(ReleaseName(ops.releaseNamePrefix + c.Title))
I was looking back at how we did this prior, and thought the same, but this is what we were doing, will fix.

2021-07-30 17:11 UTC, bkeroackdsc approved these changes

2021-07-30 17:11 UTC, esterlinej commented
Running tests before merging this into master, then will version an official release.

2021-08-04 00:07 UTC, merged